[package]
name = "dnn_dsl"
version = "0.1.0"
authors = ["tkclimb <tkclimb0911@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
paste = "0.1.3"
png = "0.13.2"
gif = "0.10.1"
llvm-sys = "70.0.1"
